name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2      
    - name: Restore packages
      run: nuget restore VATNZPlugin.csproj
    - name: Build solution
      run: msbuild VATNZPlugin.csproj /p:Configuration=Release
